name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"  # Se ejecuta cada 12 horas
  workflow_dispatch:        # Te permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Necesario para que la acción pueda actualizar el archivo
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update activity
        uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
