name: Update README

on:
  schedule:
    - cron: '0 */12 * * *'  # Se ejecuta cada 12 horas (al minuto 0)
  workflow_dispatch:        # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    permissions:
      contents: write       # IMPORTANTE: Permiso para que la acci칩n pueda editar tu README
    
    steps:
      - uses: actions/checkout@v4 # Actualizado a la versi칩n m치s reciente y estable

      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # El token debe ir DENTRO de la acci칩n que lo usa
